.\" 
.\" Copyright (c) 2008 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 2.1
.\" 
.\" Please address questions and feedback to user0@tkgeomap.org
.\" 
.\" $Id: alloc.3,v 1.5 2008/11/01 02:59:09 gcarrie Exp $
.\"
.TH alloc 3 "Allocators with optional diagnostics"
.SH NAME
MALLOC, CALLOC, REALLOC, FREE \- allocators with optional diagnostics
.SH SYNOPSIS
.nf
\fB#include "alloc.h"\fP
\fBvoid * MALLOC(size_t\fP \fIs\fP\fB);\fP
\fBvoid * CALLOC(size_t\fP \fIn\fP\fB, size_t\fP \fIs\fP\fB);\fP
\fBvoid * REALLOC(void *\fP \fIp\fP\fB, size_t\fP \fIs\fP\fB);\fP
\fBvoid FREE(void *\fP \fIp\fP\fB);\fP
.fi
.SH DESCRIPTION
These macros allocate and free memory using the standard library memory management
functions.  \fBMALLOC\fP, \fBCALLOC\fP, and \fBREALLOC\fP behave like \fBmalloc\fP,
\fBcalloc\fP, and \fBrealloc\fP, respectively, with the exception that they abort
the process if they fail.  \fBFREE\fP behaves exactly \fBfree\fP.
.SH OPTIONAL DIAGNOSTICS
If the \fBMEM_DEBUG\fP variable is defined at compile time, such as with a
line of form '\fB#define MEM_DEBUG\fP' in a header file, the macros also
arrange for output of diagnostic information.  This information normally
goes to file descriptor \fB2\fP (standard error), unless overridden by compile
time variable \fBMEM_DEBUG_OUT\fP.  The diagnostic output can help identify memory
leaks.

When \fBMALLOC\fP or \fBCALLOC\fP allocates memory with \fBMEM_DEBUG\fP defined,
it prints a line of form:

.nf
.ti +5
\fIaddress\fP \fB(\fP\fIcounter\fP\fB)\fP \fBallocated at\fP \fIfile\fP\fB:\fP\fIline\fP
.fi

Here, \fIaddress\fP is the address of the new allocation, \fIcounter\fP is
the number of times one of the allocation macros has been called, and \fIfile\fP
and \fIline\fP identify the C source file and line number where the call occurred.

If \fBREALLOC\fP returns \fIp\fP, it prints a line of form:

.nf
.ti +5
\fIaddress\fP \fB(\fP\fIcounter\fP\fB)\fP \fBreallocated at\fP \fIfile\fP\fB:\fP\fIline\fP
.fi

If \fBREALLOC\fP returns a new address, it prints two lines of form:

.nf
.in +5
\fIaddress\fP \fB(\fP\fIcounter\fP\fB)\fP \fBfreed by realloc at\fP \fIfile\fP\fB:\fP\fIline\fP
\fIaddress\fP \fB(\fP\fIcounter\fP\fB)\fP \fBallocated by realloc at\fP \fIfile\fP\fB:\fP\fIline\fP
.in -5
.fi

When \fBFREE\fP frees memory, it prints a line of form:

.nf
.ti +5
\fIaddress\fP \fB(\fP\fIcounter\fP\fB)\fP \fBfreed at\fP \fIfile\fP\fB:\fP\fIline\fP
.fi

The resulting output gives a history of allocations and calls to free made by
the process.  Script \fBmemtrace\fP can scan this output and report on
any allocations made that have not been freed when the process exits.  These
are assumed to be memory leaks, and the diagnostic output can help find where
and when they occurred.
.SH SEE ALSO
\fBmalloc\fP (3), \fBcalloc\fP (3), \fBrealloc\fP (3), \fBfree\fP (3),
\fBmemtrace\fP (1)
.SH AUTHOR
Gordon Carrie (user0@tkgeomap.org)
