.\" 
.\" Copyright (c) 2008 Gordon D. Carrie
.\" All rights reserved
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.7 $ $Date: 2008/12/17 22:55:56 $
.\"
.TH allocf 3 "Dynamic four dimensional allocators"
.SH NAME
calloc4f, free4f \- dynamic allocators for four dimensional arrays of floats
.SH SYNOPSIS
.nf
\fB#include "allocf.h"\fP
\fBfloat ****calloc4f(size_t\fP \fIl\fP, \fBsize_t\fP \fIk\fP, \fBsize_t\fP \fIj\fP, \fBsize_t\fP \fIi\fP);
\fBvoid free4f(float ****\fP\fId\fP);
.fi
.SH DESCRIPTION
These allocators create four dimensional arrays of float values.

\fBcalloc4f\fP allocates a four dimensional array of float values.  If the
return value is assigned to \fId\fP, then the highest index of the array
is \fId\fP[\fIl\fP-1][\fIk\fP-1][\fIj\fP-1][\fIi\fP-1].
terminated.
\fId\fP[\fB0\fP][\fB0\fP][\fB0\fP]  is a contiguous block of
\fIl\fP \fB*\fP \fIk\fP \fB*\fP \fIj\fP \fB*\fP \fIi\fP floats.

Each dimension array in \fId\fP is terminated with a pointer to the end of
the next dimension.  In other words,
\fBd\fP[\fIlmax\fP] points to \fBd\fP[\fIlmax\fP-1][\fIkmax\fP],
\fBd\fP[\fIlmax\fP-1][\fIkmax\fP] points to
\fBd\fP[\fIlmax\fP-1][\fIkmax\fP-1][\fIjmax\fP], and
\fBd\fP[\fIlmax\fP-1][\fIkmax\fP-1][\fIjmax\fP] points to
\fBd\fP[\fIlmax\fP-1][\fIkmax\fP-1][\fIjmax\fP-1][\fIimax\fP].
Also, \fBd\fP[\fIlmax\fP+1] is \fBNULL\fP.
This facilitates array traversal with minimal indexing.  The following loops
are equivalent.

.nf
    for (l = 0; l < lmax; l++)
	for (k = 0; k < kmax; k++)
	    for (j = 0; j < jmax; j++)
		for (i = 0; i < imax; i++)
		    use(dat[l][k][j][i]);

    for (p4 = dat; p4[1]; p4++)
	for (p3 = p4[0]; p3 < p4[1]; p3++)
	    for (p2 = p3[0]; p2 < p3[1]; p2++)
		for (p = p2[0]; p < p2[1]; p++)
		    use(*p);
.fi

The second loop might be faster for some compilers and options.

If something goes wrong, the function generates an error message that can be
retrieved with a call to \fBerr_get\fR, and returns \fBNULL\fR.

\fBfree4f\fP frees all memory associated with \fId\fP,
which should be a return value of \fBmalloc4f\fP.
.SH SEE ALSO
\fBalloc2f\fP (3), \fBalloc3f\fP (3), \fBerr_msg\fP (3), \fBallocfvi\fP (1).
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
