.\" 
.\" Copyright (c) 2008 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Id: alloc3f.3,v 1.2 2008/12/02 17:15:48 gcarrie Exp $
.\"
.TH alloc3f 3 "Dynamic three dimensional allocators"
.SH NAME
calloc3f, freef3, \- dynamic allocators for three dimensional arrays of floats
.SH SYNOPSIS
.nf
\fB#include "alloc3f.h"\fP
\fBfloat ***calloc3f(size_t\fP \fIk\fP, \fBsize_t\fP \fIj\fP, \fBsize_t\fP \fIi\fP);
\fBvoid freef3(float ***\fP\fId\fP);
.fi
.SH DESCRIPTION
These allocators create three dimensional arrays of float values.
.PP
\fBcalloc3f\fP allocates a three dimensional array of float values.  If the
return value is assigned to \fId\fP, then the highest index of the array
will be \fId\fP[\fIk\fP-1][\fIj\fP-1][\fIi\fP-1].
\fId\fP[\fB0\fP][\fB0\fP] will be a contiguous block of
\fIk\fP \fB*\fP \fIj\fP \fB*\fP \fIi\fP floats.
If something goes wrong, the function generates an error message that can be
retrieved with a call to \fBerr_get\fR, and returns \fBNULL\fR.
\fBfreef3\fP frees all memory associated with \fId\fP,
which should be a return value of \fBmalloc3f\fP.
.SH SEE ALSO
\fBMALLOC\fP (3), \fBCALLOC\fP (3), \fBREALLOC\fP (3), \fBFREE\fP (3),
\fBerr_msg\fP (3)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
