.\" 
.\" Copyright (c) 2008 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision$ $Date$
.\"
.TH err_msg 3 "Error messages"
.SH NAME
err_append, err_get \- error message generation and retrieval
.SH SYNOPSIS
.nf
\fB#include "err_msg.h"\fP
\fBvoid err_append(const char *\fP\fImsg\fP\fB);\fP
\fBchar *err_get(void);\fP
\fBvoid err_destroy(void);\fP
.fi
.SH DESCRIPTION
These functions create, modify, and retrieve a global error string.
\fBerr_append\fP appends \fImsg\fP to the global error string.

\fBerr_append\fP does not terminate messages with newlines.  The caller should
normally do this.

\fBerr_append\fP will cause the process to abort if it cannot allocate memory for
the global error message.

\fBerr_get\fP returns the global error string and then resets it, so that
subsequent calls to \fBerr_append\fP over write the previous contents.  The
value returned by \fBerr_get\fP belongs to the error message facility and
should not be modified by users.

\fBerr_destroy\fP resets the error message and frees all memory associated with
it.
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
