.\" 
.\" Copyright (c) 2008 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Id: err_msg.3,v 1.1 2008/11/15 22:47:28 gcarrie Exp $
.\"
.TH err_msg 3 "Error messages"
.SH NAME
err_append, err_get, err_destroy \- error message production and retrieval
.SH SYNOPSIS
.nf
\fB#include "err_msg.h"\fP
\fBvoid err_append(const char *\fP\fImsg\fP\fB);\fP
\fBchar *err_get(void);\fP
\fBvoid err_destroy(void);\fP
.fi
.SH DESCRIPTION
This function create, modify, and retrieve a global error string.
.PP
