.\" 
.\" Copyright (c) 2008 Gordon D. Carrie
.\" All rights reserved
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.10 $ $Date: 2009/10/07 17:06:47 $
.\"
.TH err_msg 3 "Error messages"
.SH NAME
Err_Append, Err_Get \- error message generation and retrieval
.SH SYNOPSIS
.nf
\fB#include "err_msg.h"\fP
\fBvoid Err_Append(const char *\fP\fImsg\fP\fB);\fP
\fBchar *Err_Get(void);\fP
.fi
.SH DESCRIPTION
These functions create, modify, and retrieve a global error string.

\fBErr_Append\fP appends \fImsg\fP to the global error string.  It does not
terminate messages with newlines.  The caller should normally do this.
It will cause the process to abort if it cannot allocate memory for
the global error message.

\fBErr_Get\fP returns the global error string and then resets it, so that
subsequent calls to \fBErr_Append\fP overwrite the previous contents.  The
value returned by \fBErr_Get\fP belongs to the error message facility and
should not be modified by users. If there is no error message, \fBErr_Get\fP
returns an empty string.

The error message is limited to 64 kilobytes. If it becomes longer than this,
the application prints a warning followed by the current error message, and then
the application exits.
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
