.\" 
.\" Copyright (c) 2008 Gordon D. Carrie
.\" All rights reserved
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: $ $Date: $
.\"
.TH bhead 1 "File utility"
.SH NAME
bhead \- print a number of bytes from a file.
.SH SYNOPSIS
.nf
\fBbhead\fP \fIn\fP
.fi
.SH DESCRIPTION
\fBbhead\fP prints \fIn\fP bytes from standard input to standard output.
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
