.\" 
.\" Copyright (c) 2008 Gordon D. Carrie
.\" All rights reserved
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Revision: 1.5 $ $Date: 2008/12/19 19:24:18 $
.\"
.TH chkalloc 1 "Check allocations"
.SH NAME
chkalloc \- search for leaks in output from diagnostic allocators
.SH SYNOPSIS
\fIprog\fP \fB2>&1 | chkalloc\fP
.SH DESCRIPTION
This application scans error output from \fIprog\fP.  \fIprog\fP
should manage memory only with \fBMALLOC\fP (3), \fBCALLOC\fP (3), 
\fBREALLOC\fP (3), and \fBFREE\fP (3), and it should be run with the 
\fBMEM_DEBUG\fP environment variable defined.  When \fIprog\fP
exits, \fBchkalloc\fP prints a list of any allocations that were never
freed.  These are possible memory leaks.

If environment variable \fBCHKALLOC_WARN\fP is set to \fB1\fP, and
\fBchkalloc\fP receives no input, it prints a warning and returns \fB2\fP.
.SH RETURN VALUES
.nf
\fB0\fP if input shows no evidence of memory leaks.
\fB1\fP if input shows evidence of memory leaks.
\fB2\fP if no input and \fBCHKALLOC_WARN\fP is set to \fB1\fP.
.fi
.SH SEE ALSO
\fBMALLOC\fP (3), \fBCALLOC\fP (3), \fBREALLOC\fP (3), \fBFREE\fP (3)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
