.\" 
.\" Copyright (c) 2008 Gordon D. Carrie.  All rights reserved.
.\" 
.\" Licensed under the Open Software License version 3.0
.\" 
.\" Please address questions and feedback to dev0@trekix.net
.\" 
.\" $Id: findleaks.1,v 1.6 2008/11/25 22:38:42 gcarrie Exp $
.\"
.TH findleaks 1 "Find leaks"
.SH NAME
findleaks \- search for leaks in output from diagnostic allocators
.SH SYNOPSIS
\fIprog\fP \fB2>&1 | findleaks\fP
.SH DESCRIPTION
This script scans error output from \fIprog\fP.  \fIprog\fP
should manage memory only with \fBMALLOC\fP (3), \fBCALLOC\fP (3), 
\fBREALLOC\fP (3), and \fBFREE\fP (3), and it should be run with the 
\fBMEM_DEBUG\fP environment variable defined.  When \fIprog\fP
exits, \fBfindleaks\fP prints a list of any allocations that were never
freed.  These are possible memory leaks.
.SH RETURN VALUES
If \fBfindleaks\fP finds memory leaks, it returns \fB0\fP (true).  Otherwise
it returns \fB1\fP.
.SH SEE ALSO
\fBMALLOC\fP (3), \fBCALLOC\fP (3), \fBREALLOC\fP (3), \fBFREE\fP (3)
.SH AUTHOR
Gordon Carrie (dev0@trekix.net)
