#!/usr/bin/awk -f
#
#- chkalloc --
#-	This application reads output from the diagnostic allocators.  It
#-	reports on any leaks it finds.  See chkalloc (1).
#- 
# Copyright (c) 2008 Gordon D. Carrie
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Please send feedback to dev0@trekix.net
#
# $Revision: 1.6 $ $Date: 2008/12/19 19:24:18 $

/(0x)?[0-9]+.* allocated / {
    cnt[$1]++
    tot++
}
/(0x)?[0-9]+.* freed / {
    cnt[$1]--
    tot++
}
END {
    if (ENVIRON["CHKALLOC_WARN"] && tot == 0) {
	printf "Warning chkalloc did not receive input.\n" >"/dev/stderr"
	exit 2
    }
    leak=0
    for (a in cnt) {
	if (cnt[a] > 0) {
	    printf "Leak at %s\n", a
	    leak++
	}
    }
    exit (leak == 0) ? 0 : 1
}
