#!/usr/bin/awk -f
#
#- findleaks --
#-	This script reads output from the diagnostic allocators.  It reports
#-	on any leaks it finds.  See findleaks (1).
#- 
# Copyright (c) 2008 Gordon D. Carrie
# Licensed under the Open Software License version 3.0
#
# Please send feedback to user0@tkgeomap.org
#
# $Id: findleaks,v 1.5 2008/11/23 19:41:45 gcarrie Exp $

/(0x)?[0-9]+.* allocated / {
    cnt[$1]++
}
/(0x)?[0-9]+.* freed / {
    cnt[$1]--
}
END {
    for (a in cnt) {
	if (cnt[a] > 0) {
	    printf "Leak at %s\n", a
	    exit 0
	}
    }
}
exit 1
